### ISSUE TITLE
"Label image data using GPT-4o" doesn't pick up the dataset when in "object detection" mode.

### ISSUE THREAD

**Issue by moe-sani** [edgeimpulse/llm-based-labeling#2]
Hi,
Thanks @furtiman for helping me debug this issue.

you can see the logs in the [this project](https://studio.edgeimpulse.com/studio/521355/data-sources?showPipeline=6838).

Here are the steps I tried:

1. Start a new Enterprise project and clicked "yes" when I was asked: "Are you building an object detection project?" then uploaded some data to my dataset in the project.
2. Followed the youtube guide for using GPT for labelling, so I created a transformation block and selected "Label image data using GPT-4o"
3. used the following prompt:
`What road speed limit signs do you see in this image? Respond only with the speed limit like  "30", "40", etc or "unsure" if you're not sure.`
4. Submitted the task and here is the logs:
```
Loading logs for 18648488...
Scheduling job in cluster...
Pulling container image...
Pulling container image...
Container image pulled!
Job started
Labeling unlabeled data for "Edge Impulse Inc. / GPT Labelling issue"
Prompt: "What road speed limit signs do you see in this image? Respond only with the speed limit like  "30", "40", etc or "unsure" if you\'re not sure."
Disable samples with labels: unsure
Limit no. of samples to label to: 1,000
Concurrency: 10
Auto-convert videos: No

Finding unlabeled data...
Finding unlabeled data OK (found 0 samples)

Labeling 0 samples...
[0/0] Labeling samples... (error=0)
Done labeling samples, goodbye!

Job completed (success)
```

as you can see its not picking up any images to label despite having a lot of unlabelled images in my dataset.
I later realised when I change the object detection mode to one label per item mode the problem gets resolved.

@furtiman : "This is not necessarily a bug but an issue would be to improve how the block communicated - perhaps it can log a message that the dataset is in another mode and notify the user"

**Comment by janjongboom** [comment]
We're changing this flow with AI Actions, and it will no longer find unlabeled data, but rather be explicit about what data to label (Studio is in control).
